### ISSUE TITLE
auth token is not renewed in time

### ISSUE THREAD

**Issue by bakito** [bakito/gws#80]
```
token:
  accesstoken: ya...
  tokentype: Bearer
  refreshtoken: ...
  expiry: 2025-05-21T09:14:08.7660304+02:00
  expiresin: 3599

```
